### ISSUE TITLE
Build error : com/github/gfx/powerassert/PowerAssertPlugin : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by suzukaze** [gfx/Android-Hatebulet#1]
OS: OSX
IDE: Android Studio 1.0.2
commit https://github.com/gfx/Android-Hatebulet/commit/4be73569680c3121bfdf9e202c7695aef6b7162e

```
Error:(2) A problem occurred evaluating project ':app'.
> com/github/gfx/powerassert/PowerAssertPlugin : Unsupported major.minor version 52.0
```

apply plugin: 'android-power-assert' caused build error in gradle.

build.gradle (app)

```
apply plugin: 'com.android.application'
apply plugin: 'android-power-assert'
```

build.gradle (root)

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.1.0'

        classpath 'com.github.gfx:android-power-assert-plugin:1.1.0'
    }
}

allprojects {
    repositories {
        jcenter()
    }
}
```

How do I fix it's problem ?
Thank you.

**Comment by gfx** [comment]
I can build this repo on another machine. Hmm.

Can you try Android Studio 1.1.0?

**Comment by gfx** [comment]
I got it. The error says the power-assert plugin uses Java8 feature which your JVM doesn't have.

Please upgrade your JDK.

**Comment by suzukaze** [comment]
I  upgrade from Java7 to Java8. I can build it.
Thank you.
